# backend config - for github
backend:
  name: github
  repo: gregoiredechaine/vuepress-2_dm-bim-docs
  branch: main # Brandh to update (Optional; Defaults to master)

# location of media folder
media_folder: "docs/.vuepress/public/media/"

# location of public folder
public_folder: "media/"

# publish mode for Netlify CMS
publish_mode: editorial_workflow

# config for uploadcare media library integration
media_library:
  name: uploadcare
  config:
    publicKey: 6e2a328e040d8ac99d86

# collections configuration
collections:
  # Collection for Docs
  - name: "doc" # Used in routes, e.g. /admin/collections/doc
    label: "Doc" # Used in the UI
    folder: "docs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in Front Matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  # Collection for Dynamo
  - name: "dynamo" # Used in routes, e.g. /admin/collections/view_templates
    label: "Dynamo" # Used in the UI
    folder: "docs/dynamo/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g. title.md
    fields: # The fields for each document, usually in Front Matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  # Collection for Revit
  - name: "revit" # Used in routes, e.g. /admin/collections/view_templates
    label: "Revit" # Used in the UI
    folder: "docs/revit/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in Front Matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  # Collection for Admin-Config
  - name: "admin" # Used in routes, e.g. /admin/collections/view_templates
    label: "Admin / Site Config" # Used in the UI
    files:
      - name: "sidebarEnglish"
        label: "Sidebar - English"
        file: "docs/.vuepress/configs/sidebar/english.ts" # The path to the folder where the documents are stored
        fields: # The fields for each document, usually in Front Matter
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Code", name: "code", widget: "code", default_language: "TypeScript"}